### ISSUE TITLE
Error while installing  recipe for the new JdeRobot's infrastructure for drones

### ISSUE THREAD

**Issue by jiban-jyoti** [JdeRobot/assets#18]
![Screenshot from 2019-04-04 05-52-38](https://user-images.githubusercontent.com/44982306/55505409-ad941600-5670-11e9-92b8-9b97000fb84a.png)

I faced this issue while installing the new JdeRobot's infrastructure for drones.

**Comment by nkhedekar** [comment]
@jiban-jyoti please try the procedure [detailed here](https://theroboticsclub.github.io/colab-gsoc2019-Nikhil_Khedekar/2019-05-28-installation_things_2/) instead

**Comment by pariaspe** [comment]
Stale. Updated recipe is available at academy's website.
Closing issue.
