### ISSUE TITLE
Amazon robot model update

### ISSUE THREAD

**Issue by kurshakuz** [JdeRobot/assets#30]
Additionally, I need help with the following issue: the updates that I previously made in this repository were not updated when I download and build JdeRobot package from scratch. What needs to be done to made this updates? There is something more actually than in the PR I made, and it's crucial for robot's performance

**Comment by kurshakuz** [comment]
Partially solved in https://github.com/JdeRobot/assets/pull/29

**Comment by fqez** [comment]
Hi @kurshakuz!

which changes were not updated? Can you explain a little bit more your problem? Apart from having my gazebo GUI installation broken, I've been able to launch the world with the amazon robot in it. And the sensors are working fine also (checked with `rostopic echo`)
Do you have any kind of error in your terminal?

**Comment by kurshakuz** [comment]
Hello @fqez 

Actually, the problem is related to the internal TF tree of the robot. If you try to see from your setup, your result will be different from the final setup that is required to work on the solution of the exercise.

Please have a look at your model.sdf file and if final diff_drive plugin is not as follows, there would be a couple of problems:

```
      <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
         <robotNamespace />
         <alwaysOn>true</alwaysOn>
         <updateRate>10</updateRate>
         <legacyMode>true</legacyMode>
         <leftJoint>left_wheel_joint</leftJoint>
         <rightJoint>right_wheel_joint</rightJoint>
         <wheelSeparation>0.5380</wheelSeparation>
         <wheelDiameter>0.2410</wheelDiameter>
         <torque>20</torque>
         <commandTopic>cmd_vel</commandTopic>
         <odometryTopic>odom</odometryTopic>
         <odometryFrame>odom</odometryFrame>
         <robotBaseFrame>chassis</robotBaseFrame>
         <publishWheelTF>false</publishWheelTF>
         <publishWheelJointState>false</publishWheelJointState>
         <rosDebugLevel>na</rosDebugLevel>
         <wheelAcceleration>0</wheelAcceleration>
         <wheelTorque>5</wheelTorque>
         <odometrySource>world</odometrySource>
         <publishTf>1</publishTf>
      </plugin>

```
In the end it should look like this:
![Screenshot from 2019-08-12 22-51-49](https://user-images.githubusercontent.com/28868430/74302771-d6e9fc00-4d81-11ea-90de-81923812132e.png)

**Comment by fqez** [comment]
HI! 

besides the right and left joint swapped, my sdf file is exactly the same that the one you pointed out. I already merged your PR solving the naming issue. I don't understand the second image tho.. what should I focus on?

**Comment by kurshakuz** [comment]
@fqez 

Please have a look at the following frame namings. If they are the same, then everything should be fine, and issue closed. Thanks
```
<odometryFrame>odom</odometryFrame>
<robotBaseFrame>chassis</robotBaseFrame>
```

**Comment by fqez** [comment]
yeah, they are the same :)
