### ISSUE TITLE
Build failing for Melodic

### ISSUE THREAD

**Issue by nkhedekar** [JdeRobot/assets#34]
http://build.ros.org/job/Mbin_dsv8_dSv8__jderobot_assets__debian_stretch_arm64__binary/46/console

It seems that the package was released in melodic however the dependencies may have to be changed for that.

**Comment by fqez** [comment]
Hi @nkhedekar thanks for pointing it out. As far as I've seen, ROS tries to build its packages for debian stretch also (I guess is a distribution support thing). The problem is that the default gazebo package for debian is gazebo7 while we require gazebo9 as you can see in the following image:

![imagen](https://user-images.githubusercontent.com/8070644/76649232-87554680-6560-11ea-9a9b-cc358baac729.png)

But I've no idea how to solve it... xD The only dependency I've seen in the `package.xml` is `gazebo_ros` but I'm not sure if is that the guilty dependency.

Any ideas?

**Comment by jmplaza** [comment]
In fact jderobot/assets has no dependency at all, it is a self contained package. It includes only configuration files, no code at all. @pariaspe is also looking at it

**Comment by nkhedekar** [comment]
Since these two are building fine, this probably means that we are not handling the dependancy correctly in the Cmakelists or package.xml.

http://build.ros.org/job/Mbin_dsv8_dSv8__turtlebot3_simulations__debian_stretch_arm64__binary/
http://build.ros.org/job/Mbin_ds_dS64__turtlebot3_gazebo__debian_stretch_amd64__binary/


As @jmplaza said, we do not have dependancies apart from a select few. The turtlebot dependancy is required for one of the drone exercises. Of course, in theory this repoistory should be self contained, and we can fix this by simply removing the dependancies by either omitting them or adding the repo to this one. Either one will still build, but both will be semantically incorrect. The worlds require gazebo, ros and some plugins to exist for them to be used so imo these dependancies should exist. 

We should try to figure out the error by comparing between our package and other packages downstream of turtlebot3

**Comment by nkhedekar** [comment]
As this is not a critical issue, is a build fail on debian and should be resolved by editing the Cmakelists and package.xml, I think this is a good first issue for any potential GSoCers for this year (In case we don't get around to fixing it till then :stuck_out_tongue: )

**Comment by jmplaza** [comment]
No, no, jderobot/assets has no dependency at all, both in theory and also in practice. It has no code, it is just a collection of static resources, they do not require anything else. So Cmakelists or package.xml should show that. 

assets will be used by many applications, it should not inherit their dependencies. For instance, some drone exercises in JdeRobot Academy require assets and turtlebot support but this does not imply that jderobot/assets should have that dependency itself. Each application (that drone exercise requiring the turtlebot) should have that dependency, not assets!

**Comment by jmplaza** [comment]
Gazebo plugins are code, they should not be in jderobot-assets, but in jderobot-base

**Comment by nkhedekar** [comment]
Mea culpa @jmplaza. As there are no deps, the removal of the two lines in the package.xml should resolve this (#36 ). Of course a new bloom release needs to be done to test this.

**Comment by nkhedekar** [comment]
Sorry for making a mountain of discussion over something really small. But considering that #35 comes before #36, I should have proposed my changes on it instead of making a new pull request. Mea culpa again :sweat_smile:

**Comment by jmplaza** [comment]
No problem @nkhedekar :-) We are all together building a great software!

**Comment by nkhedekar** [comment]
Thank you @ojitmehta123 for the fix. We are ready to release! 

p.s. lets keep this issue open until the build succeeds

**Comment by ojitmehta123** [comment]
My Pleasure. It was the least I could do

**Comment by nkhedekar** [comment]
Pull requests opened for re-release into both Kinetic and Melodic: 
https://github.com/ros/rosdistro/pull/24234
https://github.com/ros/rosdistro/pull/24235

**Comment by nkhedekar** [comment]
Pull request for Melodic has been merged and both debian builds are back to normal! 

[![released](http://build.ros.org/buildStatus/icon?job=Mbin_ds_dS64__jderobot_assets__debian_stretch_amd64__binary)](http://build.ros.org/job/Mbin_ds_dS64__jderobot_assets__debian_stretch_amd64__binary/) 

[![released](http://build.ros.org/buildStatus/icon?job=Mbin_dsv8_dSv8__jderobot_assets__debian_stretch_arm64__binary)](http://build.ros.org/job/Mbin_dsv8_dSv8__jderobot_assets__debian_stretch_arm64__binary/)
