### ISSUE TITLE
Add build tags to readme

### ISSUE THREAD

**Issue by nkhedekar** [JdeRobot/assets#37]
At the moment only 2 tags are mentioned in the readme, other tags should be added too to show the status of all the builds in the ros build farm. Also, the readme only mentions kinetic, even though the package is released in melodic as well. 

Lets have the gsoc applicants have a crack at this too? 

Applicants: Make the appropriate changes in the readme and open a pull request!

**Comment by dcharrezt** [comment]
Hello @nkhedekar can you please review my PR #38, thanks in advance.

**Comment by nkhedekar** [comment]
fixed in #38
