### ISSUE TITLE
Cannot launch turtlebot line following exercise

### ISSUE THREAD

**Issue by shreyasgokhale** [JdeRobot/assets#46]
Due to updates in turtlebot packages, the (undocumented) _"follow_line_turltebot"_ exercise reports `Resource not found: turtlebot_gazebo`  when launched.

**Comment by jmplaza** [comment]
Hi @shreyasgokhale, 

there are several exercises in the [RoboticsAcademy repository](https://github.com/JdeRobot/RoboticsAcademy/tree/master/exercises) outdated. Better focus on the current supported exercises, which are available at the official [Academy webpage](https://jderobot.github.io/RoboticsAcademy/) and the [exercises grid](https://jderobot.github.io/RoboticsAcademy/exercises/). The installation instructions are in [this page](https://jderobot.github.io/RoboticsAcademy/installation/). I will review your pull-request for the follow_line_turtlebot anyway :-)

**Comment by shreyasgokhale** [comment]
Hi @jmplaza 

Oh okay, I'll keep that in mind. I was just poking around😅 Thanks!
