### ISSUE TITLE
Build failing for Kinetic Xenial dev amd64

### ISSUE THREAD

**Issue by nkhedekar** [JdeRobot/assets#48]
05:13:46 The following packages have unmet dependencies:
05:13:46  ros-kinetic-catkin : Depends: python-catkin-pkg (> 0.4.3) but it is not going to be installed
05:13:46 E: Unable to correct problems, you have held broken packages.

**Comment by nkhedekar** [comment]
The issue seems to be with ros-kinetic-catkin and python-catkin-pkg. There were only readme changes in the latest update. So this means that the change only triggered a build. The actual error could be from these packages.

**Comment by jmplaza** [comment]
That is weird. In addition, assets does not explicitly depend on any other packages. Maybe we should review where we do state those dependencies and remove them.

**Comment by nkhedekar** [comment]
Yep, the only thing that is listed is catkin and that seems to be the issue.

**Comment by nkhedekar** [comment]
This [package](http://build.ros.org/job/Kdev__genpy__ubuntu_xenial_amd64/lastBuild/console), last triggered at May 12, 2020 8:27:08 PM has

python-catkin-pkg (0.4.20-100) ...
ros-kinetic-catkin (0.7.20-1xenial-20191213-232805+0000) ...

whereas our build has

ros-kinetic-catkin: 0.7.20-1xenial-20191213-232805+0000
05:13:46 Broken ros-kinetic-catkin:amd64 Depends on python-catkin-pkg [ amd64 ] < none -> 0.4.19-100 > ( python ) (> 0.4.3)

**Comment by nkhedekar** [comment]
The build for [caktin_pkg is failing](https://travis-ci.org/github/ros-infrastructure/catkin_pkg)

**Comment by nkhedekar** [comment]
As the builds for drones returned back to normal (https://github.com/JdeRobot/drones/issues/32), I think it will be the same for assets as well. Keeping this open till this happens

**Comment by pariaspe** [comment]
Yes, it seems the same.  The error must be external. Do you know how to trigger jenkins build? It is necessary to make changes on the repo?

However, it makes no sense to me that at the building those packages were needed. assets shouldn't depend on any package, right?

**Comment by nkhedekar** [comment]
So, since the drones build was triggered by the readme changes you made, I am hoping that #49 triggers a build today. 

The package which seems to have been causing the issue was the buildtool itself. Assets does not have any other dependancies.

**Comment by nkhedekar** [comment]
As Dirk mentions [here](https://answers.ros.org/question/235810/triggering-re-build-on-jenkins/), a commit on the upstream will trigger a build

**Comment by nkhedekar** [comment]
I put changes in both `master` and `kinetic-devel` (even though it is not in the rosdistro) so once the build is retriggered, we'll know which commit hash caused it. In case it is not the `kinetic-devel`, we can delete the branch as the master includes everything in it.

**Comment by nkhedekar** [comment]
Build is back to normal! 


Polling Log
View as plain text

This page captures the polling log that triggered this build.

Started on May 14, 2020 8:13:00 PM
Using strategy: Default
[poll] Last Built Revision: Revision 5d013549a3020a570bbbe15e82b40de9a3b0b3a5 (origin/master)
No credentials specified
 > git --version # timeout=10
 > git ls-remote -h https://github.com/JdeRobot/assets.git # timeout=10
Found 2 remote heads on https://github.com/JdeRobot/assets.git
[poll] Latest remote head revision on refs/heads/master is: 5ea880f74f08d410898be3aa2817860bace6e5b3
Done. Took 5.3 sec
Changes found


This means the build was due to `master`. Deleting `kinetic-devel` and closing this.
