### ISSUE TITLE
Setting up build farm for ROS Noetic

### ISSUE THREAD

**Issue by shreyasgokhale** [JdeRobot/assets#52]
From what I gather, this repo is the source for [jderobot_assets ros builds](http://jenkins.ros.org/job/Msrc_uB__jderobot_assets__ubuntu_bionic__source/). But I'd like to know more about the build procedure and scripts in order to use the assets in ROS Noetic.

**Comment by pariaspe** [comment]
Hi @shreyasgokhale,

As the README says, _This repository contains all models and worlds required by the JdeRobot exercises._
I would also add launch files, perspectives and urdf files. Anyway, there is **no** source code, so the jump to ROS Noetic is not a big thing in this package.

**Comment by shreyasgokhale** [comment]
Hi @pariaspe, thanks for the reply. I have updated the package.xml according to the ROS Noetic migration [guide](http://wiki.ros.org/noetic/Migration) in [here](https://github.com/shreyasgokhale/assets/tree/noetic-master). But it is working the either way. 

Should I create a PR so that Noetic can be included in distro support?

**Comment by pariaspe** [comment]
Hi @shreyasgokhale, 

There is a release automatic tool ([bloom](http://wiki.ros.org/bloom)) to create packages. Check this [tutorial](http://wiki.ros.org/bloom/Tutorials/ReleasingForANewROSDistro) to release a pkg into a new ROS distro. I've used it before migrating some pkg from kinetic to melodic, so ask me if you have any problem, I might help :)

Yes, a PR is needed. However, it may be created automatically with bloom tool. For this, make sure that you have the two-factor authentication enabled for github ([tutorial](http://wiki.ros.org/bloom/Tutorials/GithubManualAuthorization)).

**Comment by shreyasgokhale** [comment]
Hi @pariaspe 

Thanks! I am getting access denied error for `assets-release` repo.

```
ERROR: Permission to JdeRobot/assets-release.git denied to shreyasgokhale.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
I have configured the git according to the tutorial. Should I try bloom with on my forked repo as `upstream devel branch`?

Also, how to create PRs for the branches which do not exist in forked upstreams?

[errorlog.txt](https://github.com/JdeRobot/assets/files/4711076/errorlog.txt)

**Comment by jmplaza** [comment]
Hi @shreyasgokhale , try now

**Comment by pariaspe** [comment]
Hi again @shreyasgokhale,

It's normal, you don't have write permissions on the repo. Hope @jmplaza can fix this.

As far as I know, you should make the bloom release over this repo instead your forked one. At least, I've never tried to do it.

**Comment by shreyasgokhale** [comment]
Thanks @jmplaza ! I got it.

Can you also give me the permissions for this repo, so that I can create a noetic-devel branch and  push the updates there?

**Comment by jmplaza** [comment]
Done. Check now

**Comment by pariaspe** [comment]
Done. Thanks @shreyasgokhale
